### ISSUE TITLE
nrf52832_periph code crashes before main when nordic_softdevice_ble package is included.

### ISSUE THREAD

**Issue by VilleHiltunen** [VilleHiltunen/RIOT#1]
#### Description
The code in nrf52832_periph works normally when softdevice is not present. If USEPKG += nordic_softdevice_ble is added to the Makefile, the application crashes before main.

#### Steps to reproduce the issue
`cd nrf52832_periph`
`make flash`

#### Expected results
Prints through UART at 115200 BAUD and flashes onboard LED.

#### Actual results
Apparently crashes before reaching main.
Stack trace looks like the following:
```
Connecting to J-Link...
Reading symbols from /home/teppo/Desktop/riot/RIOT/nrf52832_periph/bin/nrf52832/Sauva.elf...done.
J-Link is connected.
Firmware: J-Link OB-SAM3U128-V2-NordicSemi compiled Jan 12 2018 16:05:20
Hardware: V1.00
S/N: 682233346
Checking target voltage...
Target voltage: 3.30 V
Listening on TCP/IP port 3333
Connecting to target...Connected to target
Waiting for GDB connection...Remote debugging using :3333
Connected to 127.0.0.1
Reading all registers
Read 4 bytes @ address 0x0001FE42 (Data = 0x411CF8D3)
Reading 64 bytes @ address 0x20004680
Read 4 bytes @ address 0x0001F5DE (Data = 0xBD104620)
Read 4 bytes @ address 0x00024D2C (Data = 0xDC062800)
uart_write (uart=uart@entry=0, data=<optimized out>, len=len@entry=23)
    at /home/teppo/Desktop/riot/RIOT/cpu/nrf5x_common/periph/uart.c:177
177	            while (NRF_UART0->EVENTS_TXDRDY == 0) {}
(gdb) where
#0  uart_write (uart=uart@entry=0, data=<optimized out>, len=len@entry=23)
    at /home/teppo/Desktop/riot/RIOT/cpu/nrf5x_common/periph/uart.c:177
#1  0x0001f5de in uart_stdio_write (buffer=<optimized out>, len=23)
    at /home/teppo/Desktop/riot/RIOT/sys/uart_stdio/uart_stdio.c:118
#2  0x00024d2c in __sflush_r ()
Read 4 bytes @ address 0x00024B2A (Data = 0xE00FB190)
#3  0x00024b2a in __swbuf_r ()
Reading 64 bytes @ address 0x200046C0
Read 4 bytes @ address 0x00025198 (Data = 0xD1F31C43)
#4  0x00025198 in __sfputs_r ()
Read 4 bytes @ address 0x00025200 (Data = 0xF0003001)
#5  0x00025200 in _vfprintf_r ()
Reading 64 bytes @ address 0x20004740
Read 4 bytes @ address 0x000249EA (Data = 0xE8BDB002)
#6  0x000249ea in printf ()
Reading 64 bytes @ address 0x20004780
Read 4 bytes @ address 0x0001F9C2 (Data = 0xF0054806)
Read 4 bytes @ address 0x0001F382 (Data = 0x5836BF00)
#7  0x0001f9c2 in core_panic (crash_code=crash_code@entry=PANIC_HARD_FAULT, 
Reading 8 bytes @ address 0x00025836
Reading 8 bytes @ address 0x0002583E
Reading 8 bytes @ address 0x00025846
    message=message@entry=0x25836 "HARD FAULT HANDLER")
    at /home/teppo/Desktop/riot/RIOT/core/panic.c:61
#8  0x0001f382 in hard_fault_default ()
    at /home/teppo/Desktop/riot/RIOT/cpu/cortexm_common/vectors_cortexm.c:339
Read 4 bytes @ address 0x200047C4 (Data = 0x0100000B)
#9  <signal handler called>
Reading 64 bytes @ address 0x200047C0
Read 4 bytes @ address 0x0001F356 (Data = 0xE8B1C901)
#10 0x0001f356 in isr_svc ()
    at /home/teppo/Desktop/riot/RIOT/cpu/cortexm_common/thread_arch.c:334
Read 4 bytes @ address 0x0001F350 (Data = 0x68004804)
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by haukepetersen** [comment]
Hi, thanks for posting this and welcome to RIOT!

Just for completeness, you are using this branch and for here, right?
https://github.com/VilleHiltunen/RIOT/tree/master/nrf52832_periph

**Comment by haukepetersen** [comment]
After some debugging, seems to me that https://github.com/RIOT-OS/RIOT/pull/8068 solves this issue.

@VilleHiltunen can you confirm this?

**Comment by VilleHiltunen** [comment]
Confirmed. Sorry I was watching only my email, not github. Thanks for help.
